package com.github.jparound30.idea.plugin.stepcounter.ui;

import com.github.jparound30.idea.plugin.stepcounter.action.StepCountAction;
import com.intellij.ui.components.JBScrollPane;
import com.intellij.ui.table.JBTable;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import jp.sf.amateras.stepcounter.diffcount.object.DiffFileResult;

import javax.swing.*;
import java.awt.*;

/**
 * @author jparound30
 */
public class StepDiffView {
    private JTable tableView;
    private JButton Cancel;
    private JButton Save;
    private JPanel rootPanel;

    public StepDiffView(java.util.List<DiffFileResult> data) {
        $$$setupUI$$$();
        StepCountAction.DiffTableMode tableModel = new StepCountAction.DiffTableMode(data);
        tableView.setModel(tableModel);
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
        final JBScrollPane jBScrollPane1 = new JBScrollPane();
        rootPanel.add(jBScrollPane1, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        tableView = new JBTable();
        tableView.setPreferredScrollableViewportSize(new Dimension(980, 400));
        tableView.putClientProperty("html.disable", Boolean.FALSE);
        jBScrollPane1.setViewportView(tableView);
        Cancel = new JButton();
        Cancel.setText("Cancel");
        rootPanel.add(Cancel, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        Save = new JButton();
        Save.setText("Save");
        rootPanel.add(Save, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }
}
